Update README.md
so this tutorial its bit changed you just need to cargo install and add the path

error: Using `cargo install` to install the binaries from the package in current working directory is no longer supported, use `cargo install --path .` instead. Use `cargo build` if you want to simply build the package.